import { memo, useState } from "react"
import { Card } from "@/components/ui/card"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { EmptyState } from "@/components/EmptyState"
import { LoadingState } from "@/components/LoadingState"
import { cn } from "@/lib/utils"
import { type ResultImage } from "@/types/results"
import { Images, ImageOff, Maximize2 } from "lucide-react"

interface ResultsGalleryProps {
  results: ResultImage[]
}

function ChartPlaceholder({ seed }: { seed: string }) {
  // Deterministic pseudo-random bars/line based on the id, so each card looks distinct but stable
  const hash = seed.split("").reduce((acc, c) => acc + c.charCodeAt(0), 0)
  const points = Array.from({ length: 8 }, (_, i) => 20 + ((hash * (i + 1)) % 60))
  const path = points.map((p, i) => `${i === 0 ? "M" : "L"} ${i * 14} ${80 - p}`).join(" ")

  return (
    <svg viewBox="0 0 100 80" className="h-full w-full">
      <path d={path} fill="none" stroke="var(--color-primary)" strokeWidth="2" opacity="0.7" />
      {points.map((p, i) => (
        <circle key={i} cx={i * 14} cy={80 - p} r="1.5" fill="var(--color-primary)" />
      ))}
    </svg>
  )
}

function ResultsGalleryComponent({ results }: ResultsGalleryProps) {
  const [preview, setPreview] = useState<ResultImage | null>(null)

  if (results.length === 0) {
    return (
      <EmptyState
        icon={Images}
        title="No results yet"
        description="Evaluation charts generated by the backend will appear here"
      />
    )
  }

  return (
    <>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {results.map((result) => (
          <Card
            key={result.id}
            className={cn(
              "overflow-hidden p-0",
              result.status === "ready" && "cursor-pointer card-interactive"
            )}
            onClick={() => result.status === "ready" && setPreview(result)}
          >
            <div className="relative flex h-28 items-center justify-center bg-accent/50 px-4">
              {result.status === "ready" && <ChartPlaceholder seed={result.id} />}
              {result.status === "loading" && <LoadingState rows={3} className="w-full px-2" />}
              {result.status === "missing" && (
                <div className="flex flex-col items-center gap-1.5 text-muted-foreground">
                  <ImageOff className="h-5 w-5" />
                  <p className="text-[10px]">Not generated yet</p>
                </div>
              )}
              {result.status === "ready" && (
                <div className="absolute right-2 top-2 rounded-md bg-background/80 p-1">
                  <Maximize2 className="h-3 w-3 text-muted-foreground" />
                </div>
              )}
            </div>
            <div className="p-3">
              <p className="text-xs font-semibold">{result.title}</p>
              <p className="mt-0.5 text-[10px] text-muted-foreground">{result.description}</p>
            </div>
          </Card>
        ))}
      </div>

      <Dialog open={preview !== null} onOpenChange={(open) => !open && setPreview(null)}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>{preview?.title}</DialogTitle>
            <DialogDescription>{preview?.description}</DialogDescription>
          </DialogHeader>
          <div className="flex h-64 items-center justify-center rounded-lg bg-accent/50 px-6">
            {preview && <ChartPlaceholder seed={preview.id} />}
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}

export const ResultsGallery = memo(ResultsGalleryComponent)
